<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Admin / Kepala Sekolah
        User::create([
            'id' => Str::uuid(),
            'name' => 'Kepala Sekolah',
            'nik' => '987654',
            'jabatan' => 'admin',
            'password' => Hash::make('987654'),
        ]);

        // Generate 15 Gurus
        $gurus = [
            'Budi Santoso', 'Siti Aminah', 'Ujang Surahman', 'Rina Marlina', 'Agus Setiawan',
            'Dewi Lestari', 'Eko Prasetyo', 'Fina Meliana', 'Gilang Ramadhan', 'Hendra Wijaya',
            'Irma Yuliana', 'Joko Widodo', 'Kartika Sari', 'Lukman Hakim', 'Nia Ramadhani'
        ];

        foreach ($gurus as $index => $guruName) {
            $nik = str_pad($index + 1, 6, '0', STR_PAD_LEFT);
            User::create([
                'id' => Str::uuid(),
                'name' => 'Pak/Bu ' . explode(' ', $guruName)[0],
                'nik' => $nik,
                'jabatan' => 'guru',
                'password' => Hash::make($nik),
            ]);
        }

        // Ketua kelas will be generated by MuridSeeder or KelasSeeder later.
    }
}
